# Generated by Django 6.1 on 2026-08-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio shown on the public Team Members section.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.CharField(blank=True, help_text='e.g. Research & Publications', max_length=255),
        ),
    ]
