# Generated by Django 6.1 on 2026-08-18 22:01

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('passport_photo', models.ImageField(upload_to='applications/passport_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), applications.models.validate_file_size])),
                ('cv_transcript', models.FileField(upload_to='applications/cv_transcripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('approved', 'Approved')], default='pending', max_length=15)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
    ]
