# Generated by Django 6.1 on 2026-08-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='statement_of_purpose',
            field=models.TextField(blank=True, help_text="Applicant's statement of purpose / motivation letter."),
        ),
    ]
