# Generated by Django 6.1 on 2026-08-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_statement_of_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='course_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='level',
            field=models.CharField(blank=True, help_text='e.g. 300 Level, Year 3', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
