# Generated by Django 6.1 on 2026-08-27 01:05

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_course_of_study_application_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cgpa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='statement_of_purpose',
            field=models.FileField(upload_to='statement_of_purpose', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size]),
        ),
    ]
