# Generated by Django 6.1 on 2026-08-27 01:16

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='statement_of_purpose',
            field=models.FileField(upload_to='applications/statement_of_purpose', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size]),
        ),
    ]
