# Generated by Django 6.1 on 2026-09-10 21:38

import applications.models
import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_statement_of_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_transcript',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='applications/cv_transcripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_photo',
            field=models.ImageField(max_length=500, upload_to='applications/passport_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), applications.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='statement_of_purpose',
            field=models.FileField(max_length=500, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='applications/statement_of_purpose', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), applications.models.validate_file_size]),
        ),
    ]
