# Generated by Django 6.1 on 2026-08-18 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('author_name', models.CharField(help_text='The actual writer of the article — may differ from the person uploading it.', max_length=255)),
                ('summary', models.TextField(help_text='Short description/abstract of the article.')),
                ('pdf_file', models.FileField(upload_to='articles/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('date_written', models.DateField(help_text='The date the article was originally written by the author.')),
                ('date_posted', models.DateTimeField(auto_now_add=True, help_text='Automatically set when the article is uploaded to the platform.')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
