# Generated by Django 6.1 on 2026-08-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='institution',
            field=models.CharField(blank=True, help_text='e.g. Elizade University Faculty of Law', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages in the PDF.', null=True),
        ),
    ]
