# Generated by Django 6.1 on 2026-08-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/covers/'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
