# Generated by Django 6.1 on 2026-08-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_alter_programme_cover_image_alter_programme_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('completed', 'Completed'), ('other', 'Other')], default='upcoming', max_length=10),
        ),
    ]
