# Generated by Django 6.1 on 2026-08-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_alter_programme_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('completed', 'Completed')], default='upcoming', max_length=10),
        ),
    ]
