# Generated by Django 6.1 on 2026-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office', models.CharField(blank=True, help_text='e.g. Research & Publications', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='Phone number or email', max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/photos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
