# Generated by Django 6.1 on 2026-08-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('competition', 'Competition')], max_length=20)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('details_url', models.URLField(blank=True, help_text="External link for 'View Details', if applicable.")),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
