# Generated by Django 6.1 on 2026-08-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegiumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='collegium/photos/')),
                ('school', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['member_name'],
            },
        ),
    ]
