# Generated by Django 6.1 on 2026-08-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegiummember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio shown on the public Collegium section.'),
        ),
    ]
