# Generated by Django 6.1 on 2026-08-25 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservatoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('research', 'Research'), ('essays', 'Essays'), ('student_voices', 'Student Voices'), ('interviews', 'Interviews'), ('publications', 'Publications')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Full body content of the post.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='observatory/covers/')),
                ('read_time_minutes', models.PositiveIntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
